import type { GlobalThemeOverrides } from 'naive-ui'

/** Naive UI token 對齊 apps/admin/src/assets/main.css 的手刻視覺規格。 */
export const adminTheme: GlobalThemeOverrides = {
  common: {
    fontFamily: "'Noto Sans TC', sans-serif",
    fontFamilyMono: 'monospace',
    primaryColor: '#c9a24b',
    primaryColorHover: '#d7b45d',
    primaryColorPressed: '#a87f2f',
    primaryColorSuppl: '#c9a24b',
    infoColor: '#c9a24b',
    infoColorHover: '#d7b45d',
    infoColorPressed: '#a87f2f',
    errorColor: '#b85a4a',
    errorColorHover: '#c76b5b',
    errorColorPressed: '#9d493c',
    textColorBase: '#2a2622',
    textColor1: '#2a2622',
    textColor2: '#6b5a48',
    textColor3: '#8a7d68',
    bodyColor: '#f2efea',
    cardColor: '#fff',
    modalColor: '#fff',
    popoverColor: '#fff',
    borderColor: '#e6e1d8',
    borderRadius: '7px',
    borderRadiusSmall: '6px',
    fontSize: '14px',
    fontSizeSmall: '13px',
    heightMedium: '42px',
  },
  Button: {
    borderRadiusMedium: '7px',
    fontWeight: '500',
    paddingMedium: '10px 22px',
    textColorPrimary: '#3a211c',
    textColorHoverPrimary: '#3a211c',
    textColorPressedPrimary: '#3a211c',
    colorPrimary: '#c9a24b',
    colorHoverPrimary: '#d7b45d',
    colorPressedPrimary: '#a87f2f',
    borderPrimary: '1px solid #c9a24b',
    borderHoverPrimary: '1px solid #d7b45d',
    borderPressedPrimary: '1px solid #a87f2f',
  },
  DataTable: {
    thColor: '#fbf8f2',
    thTextColor: '#8a7d68',
    tdTextColor: '#2a2622',
    borderColor: '#ece6dc',
    tdColorHover: '#fdfcf8',
    borderRadius: '12px',
    fontSizeMedium: '14px',
    thFontWeight: '400',
  },
  DatePicker: {
    peers: {
      Input: {
        border: '1px solid #dad3c8',
        borderHover: '1px solid #c9a24b',
        borderFocus: '1px solid #c9a24b',
        boxShadowFocus: '0 0 0 2px rgba(201, 162, 75, 0.16)',
        borderRadius: '7px',
        heightMedium: '42px',
      },
    },
  },
  Dialog: {
    borderRadius: '12px',
    titleFontSize: '18px',
    titleTextColor: '#3a211c',
    textColor: '#6b5a48',
    padding: '24px 26px',
  },
  Pagination: {
    itemTextColorActive: '#3a211c',
    itemColorActive: '#f2e4c8',
    itemBorderActive: '1px solid #c9a24b',
    buttonBorder: '1px solid #dad3c8',
    buttonBorderHover: '1px solid #c9a24b',
    buttonIconColorHover: '#c9a24b',
  },
}
