#!/usr/bin/env node
/* global console, process */
import { execFileSync } from 'node:child_process'
import { mkdirSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'

const DEFAULT_SOURCE_DIR = '/Users/ray.shao/Downloads/華圓覺苑網站/法寶略節'
const SOURCE_DIR = process.argv[2] ?? DEFAULT_SOURCE_DIR
const OUT_FILE =
  process.argv[3] ?? 'supabase/migrations/20260706120000_create_sutras_library.sql'

const HEART_SUTRA = {
  seq: 18,
  title: '般若波羅蜜多心經',
  translator: '唐三藏法師玄奘奉詔譯',
  content: [
    '觀自在菩薩，行深般若波羅蜜多時，照見五蘊皆空，度一切苦厄。',
    '舍利子，色不異空，空不異色，色即是空，空即是色，受想行識，亦復如是。',
    '舍利子，是諸法空相，不生不滅，不垢不淨，不增不減。',
    '是故空中無色，無受想行識，無眼耳鼻舌身意，無色聲香味觸法，',
    '無眼界，乃至無意識界，無無明，亦無無明盡，乃至無老死，亦無老死盡。',
    '無苦集滅道，無智亦無得，以無所得故，菩提薩埵，依般若波羅蜜多故，',
    '心無罣礙，無罣礙故，無有恐怖，遠離顛倒夢想，究竟涅槃。',
    '三世諸佛，依般若波羅蜜多故，得阿耨多羅三藐三菩提。',
    '故知般若波羅蜜多，是大神咒，是大明咒，是無上咒，是無等等咒，',
    '能除一切苦，真實不虛。故說般若波羅蜜多咒，即說咒曰：',
    '揭帝揭帝，般羅揭帝，般羅僧揭帝，菩提僧莎訶。',
  ].join('\n'),
}

function sql(value) {
  if (value === null || value === undefined) return 'null'
  return `'${String(value).replaceAll("'", "''")}'`
}

function txtFromDocx(file) {
  return execFileSync('textutil', ['-convert', 'txt', '-stdout', file], {
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 20,
  }).replace(/\r\n?/g, '\n')
}

function trimOuterBlankLines(lines) {
  let start = 0
  let end = lines.length
  while (start < end && lines[start].trim() === '') start += 1
  while (end > start && lines[end - 1].trim() === '') end -= 1
  return lines.slice(start, end)
}

function parseDocx(file) {
  const filename = basename(file)
  const seq = Number(filename.match(/^(\d+)\./)?.[1])
  let text = txtFromDocx(file)
  const warnings = []

  if (filename.startsWith('3.')) {
    if (text.includes('𠯋')) {
      text = text.replaceAll('𠯋', '(口+陀)')
    }
    warnings.push(`${filename}: contains 陀.jpg rare glyph; replaced 𠯋 with (口+陀).`)
  }

  if (filename.startsWith('15.')) {
    text = text.replace('食   飲漿', '食麨飲漿').replace('王食  蜜', '王食麨蜜')
    warnings.push(`${filename}: contains 麨.jpg rare glyph; inserted 麨 (U+9EA8).`)
  }

  const lines = trimOuterBlankLines(text.split('\n'))
  const titleIndex = lines.findIndex((line) => line.trim())
  if (titleIndex < 0 || !seq) throw new Error(`Unable to parse ${filename}`)

  const title = lines[titleIndex].trim().replace(/^《(.+)》$/, '$1')
  const maybeTranslatorIndex = lines.findIndex((line, index) => index > titleIndex && line.trim())
  const maybeTranslator = maybeTranslatorIndex >= 0 ? lines[maybeTranslatorIndex].trim() : ''
  const hasTranslator = /譯|译/.test(maybeTranslator)
  const contentStart = hasTranslator ? maybeTranslatorIndex + 1 : titleIndex + 1
  const content = trimOuterBlankLines(lines.slice(contentStart)).join('\n')

  if (!content) throw new Error(`No content parsed for ${filename}`)

  return {
    seq,
    title,
    translator: hasTranslator ? maybeTranslator : null,
    content,
    warnings,
  }
}

const docxFiles = readdirSync(SOURCE_DIR)
  .filter((name) => /^\d+\..+\.docx$/i.test(name))
  .sort((a, b) => Number(a.match(/^(\d+)/)[1]) - Number(b.match(/^(\d+)/)[1]))
  .map((name) => join(SOURCE_DIR, name))

if (docxFiles.length !== 17) {
  throw new Error(`Expected 17 docx files in ${SOURCE_DIR}, found ${docxFiles.length}`)
}

const rows = [...docxFiles.map(parseDocx), HEART_SUTRA]
const warnings = rows.flatMap((row) => row.warnings ?? [])

const valuesSql = rows
  .map(
    (row) =>
      `  (${row.seq}, ${sql(row.title)}, ${sql(row.translator)}, ${sql(row.content)}, '已發布')`,
  )
  .join(',\n')

const migration = `-- sutra-library:經文庫表、RLS 與一次性 seed
-- Generated by scripts/import-sutras.mjs from ${SOURCE_DIR}

create table if not exists public.sutras (
  id bigint generated always as identity primary key,
  seq integer not null unique,
  title text not null,
  translator text,
  content text not null,
  status text not null default '草稿' check (status in ('草稿', '已發布')),
  created_at timestamptz not null default now()
);

create index if not exists sutras_status_seq_idx on public.sutras (status, seq);

alter table public.sutras enable row level security;

grant select on public.sutras to anon;
grant select, insert, update, delete on public.sutras to authenticated;
grant select, insert, update, delete on public.sutras to service_role;
grant usage, select on sequence public.sutras_id_seq to authenticated, service_role;

drop policy if exists "public read published sutras" on public.sutras;
create policy "public read published sutras"
  on public.sutras
  for select
  to anon
  using (status = '已發布');

drop policy if exists "admin full access sutras" on public.sutras;
create policy "admin full access sutras"
  on public.sutras
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

insert into public.sutras (seq, title, translator, content, status)
values
${valuesSql}
on conflict (seq) do update set
  title = excluded.title,
  translator = excluded.translator,
  content = excluded.content,
  status = excluded.status;

notify pgrst, 'reload schema';
`

mkdirSync(join(process.cwd(), 'supabase/migrations'), { recursive: true })
writeFileSync(OUT_FILE, migration)

for (const warning of warnings) console.warn(`WARNING: ${warning}`)
console.log(`Wrote ${OUT_FILE} with ${rows.length} sutras.`)
